Traceback (most recent call last):
  File "G:/IM/10-Projects/16.02-AMF/P6 GUI development/ver2 Page/unknown.py", line 247, in <module>
    vp_start_gui()
  File "G:/IM/10-Projects/16.02-AMF/P6 GUI development/ver2 Page/unknown.py", line 28, in vp_start_gui
    top = TopLevel1 (root)
  File "G:/IM/10-Projects/16.02-AMF/P6 GUI development/ver2 Page/unknown.py", line 208, in __init__
    self._img1 = tk.PhotoImage(file="./project.jpg")
  File "C:\APPS\Python364\lib\tkinter\__init__.py", line 3539, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\APPS\Python364\lib\tkinter\__init__.py", line 3495, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "./project.jpg"
